#!/bin/bash
set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <input> <output>"
    exit -1
fi

input="$1"
output="$2"
tmpdir=/tmp/$(basename $0).$$
mkdir -p $tmpdir

# Validate that there's exactly one Track element
trackcount=$(xml sel -t -v "count(//*[local-name()='Track'])" "$input")
if [ $trackcount -ne 1 ]; then
    echo "ERROR: expected exactly one Track element; found $trackcount"
    exit -2
fi

# Extract the data we care about into a set of files
xml sel -t -m "//*[local-name()='Track']/*[local-name()='when']/text()" -c . -n "$1" > $tmpdir/when
xml sel -t -m "//*[local-name()='Track']/gx:coord/text()" -c . -n "$1" > $tmpdir/coord
prefix="//*[local-name()='Track']/*[local-name()='ExtendedData']/*[local-name()='SchemaData']/gx:SimpleArrayData[@name='"
suffix="']/gx:value/text()"
xml sel -t -m "${prefix}Heartrate${suffix}" -c . -n "$1" > $tmpdir/hr
xml sel -t -m "${prefix}Cadence${suffix}" -c . -n "$1" > $tmpdir/cadence
xml sel -t -m "${prefix}Distance${suffix}" -c . -n "$1" > $tmpdir/distance
xml sel -t -m "${prefix}Power${suffix}" -c . -n "$1" > $tmpdir/power

echo '<?xml version="1.0" encoding="utf-8"?>
<gpx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.cluetrust.com/XML/GPXDATA/1/0 http://www.cluetrust.com/Schemas/gpxdata10.xsd" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0" version="1.1" creator="Movescount - http://www.movescount.com" xmlns="http://www.topografix.com/GPX/1/1">
  <trk>
    <name>Move</name>
    <trkseg>' > "$tmpdir/out"

awk "BEGIN {OFS=\"\"}{
  getline coordline < \"$tmpdir/coord\"
  split(coordline, coords, \" \")  

  getline hrline < \"$tmpdir/hr\"
  getline cadenceline < \"$tmpdir/cadence\"
  getline distanceline < \"$tmpdir/distance\"
  getline powerline < \"$tmpdir/power\"

  print \"<trkpt lat='\",coords[2],\"'\",\" lon='\",coords[1],\"'>\"
  print \"<ele>\",coords[3],\"</ele>\"
  print \"<time>\",\$1,\"</time>\"
  print \"<extensions><gpxdata:hr>\",hrline,\"</gpxdata:hr>\"
  print \"<gpxdata:cadence>\",cadenceline,\"</gpxdata:cadence>\"
  print \"<gpxdata:distance>\",distanceline,\"</gpxdata:distance>\"
  print \"<power>\",powerline,\"</power></extensions></trkpt>\"
}" $tmpdir/when >> "$tmpdir/out"

echo "</trkseg>
  </trk>
</gpx>" >> "$tmpdir/out"
xmllint --format "$tmpdir/out" > "$output"

rm -rf $tmpdir
